name: 'auto release'
description: 'auto release'
inputs:
  tag:  # tag
    description: 'release tag name'
    required: true
  github_token:
    description: 'github token'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'